[package]
name = "arcana"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "Arcana Engine Runtime"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
arcana-alloc = { path = "../alloc" }
arcana-assets = { path = "../assets" }
arcana-base-encoding = { path = "../base-encoding" }
arcana-ecs = { path = "../ecs" }
arcana-error = { path = "../error" }
arcana-graphics = { path = "../graphics" }
arcana-hash = { path = "../hash" }
arcana-id = { path = "../id" }
arcana-input = { path = "../input" }
arcana-intern = { path = "../intern" }
arcana-io = { path = "../io" }
arcana-model = { path = "../model" }
arcana-metatype = { path = "../metatype" }
arcana-num2name = { path = "../num2name" }
arcana-plugin = { path = "../plugin" }
arcana-proc = { path = "../proc" }
arcana-project = { path = "../project" }
arcana-unfold = { path = "../unfold" }
arcana-work-graph = { path = "../work-graph" }

athena.workspace = true
bytemuck.workspace = true
gametime.workspace = true
hashbrown.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true
mev.workspace = true
smol_str.workspace = true
