[package]
name = "arcana"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "Arcana Engine"

[features]
derive = ["dep:arcana-proc"]

# Enables multi-threaded runtime for tokio.
multi-thread = ["tokio/rt-multi-thread"]

# Adds game client modules
client = ["dep:winit", "dep:mev", "dep:gilrs"]
server = []

app = ["client", "dep:miette", "dep:serde", "dep:serde_json", "winit/serde"]

ed = [
    "app",
    "server",
    "dep:arcana-project",
    "dep:arcana-importers",
    "dep:argosy-store",
    "dep:rfd",
]

[dependencies]
arcana-proc = { path = "proc", optional = true }
arcana-project = { path = "../project", optional = true }
arcana-importers = { path = "../importers", optional = true }
mev = { path = "../mev", optional = true }

approx = { workspace = true }
argosy = { workspace = true }
argosy-store = { workspace = true, optional = true }
base64 = { workspace = true }
blink-alloc = { workspace = true }
bit-vec = { workspace = true }
bytemuck = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
edict = { workspace = true }
egui = { workspace = true }
egui_dnd = { workspace = true }
egui_dock = { workspace = true, features = ["serde"] }
egui-phosphor = { workspace = true }
egui_tracing = { workspace = true }
egui-winit = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
gametime = { workspace = true }
gilrs = { workspace = true, optional = true }
hashbrown = { workspace = true, features = ["serde"] }
libloading = { workspace = true }
miette = { workspace = true, features = ["fancy"], optional = true }
na = { workspace = true, features = ["libm"] }
parking_lot = { workspace = true }
rand = { workspace = true }
rapid-qoi = { workspace = true }
rfd = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true }
simba = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true }
winit = { workspace = true, optional = true }
