name = "example"

[engine]
path = "../crates/arcana"

[[plugins]]
name = "triangle"
description = ""

[plugins.dependency]
path = "../crates/plugins/triangle"

[[plugins]]
name = "dummy"
description = ""

[plugins.dependency]
path = "../crates/plugins/dummy"
