name = "aaa"

[engine]
path = "../crates/arcana"

[[plugins]]
name = "dummy"
description = ""

[plugins.dependency]
path = '..\crates\plugins\dummy'

[[plugins]]
name = "triangle"
description = ""

[plugins.dependency]
path = '..\crates\plugins\triangle'
