name = "aaa"

[engine]
path = "../crates/arcana"

[[plugins]]
name = "scene"
description = ""

[plugins.dependency]
path = '..\crates\plugins\scene'

[[plugins]]
name = "triangle"
description = ""

[plugins.dependency]
path = '..\crates\plugins\triangle'

[[plugins]]
name = "dummy"
description = ""

[plugins.dependency]
path = '..\crates\plugins\dummy'
