name = "aaa"

[engine]
path = '..\crates\arcana'

[[plugins]]
name = "triangle"
description = ""

[plugins.dependency]
path = '..\crates\plugins\triangle'

[[plugins]]
name = "dummy"
description = ""

[plugins.dependency]
path = '..\crates\plugins\dummy'

[[plugins]]
name = "square"
description = ""

[plugins.dependency]
path = '..\crates\plugins\square'
