[package]
name = "arcana-model"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "Defines a model and a value type for type-erased communications"

[dependencies]
arcana-intern = { path = "../intern" }
arcana-base-encoding = { path = "../base-encoding" }
arcana-id = { path = "../id" }

athena = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
palette.workspace = true
hashbrown.workspace = true
thiserror.workspace = true
foldhash.workspace = true
smol_str = { workspace = true, features = ["serde"] }
gametime = { workspace = true, features = ["serde"] }
