[package]
name = "arcana-assets"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "Asset pipeline and loader for Arcana engine"

[dependencies]
arcana-intern = { path = "../intern" }
arcana-error = { path = "../error" }
arcana-id = { path = "../id" }
arcana-metatype = { path = "../metatype" }

mev.workspace = true

futures.workspace = true
thiserror.workspace = true
amity = { workspace = true, features = ["flip-queue"] }
hashbrown.workspace = true
parking_lot.workspace = true
tokio.workspace = true
