/// Time based ID generator.
/// Uses seconds since predefined moment as a base for ID values.
/// Adds counter for sub-second generated IDs.
/// And generator ID to avoid collisions between different instances.
pub struct TimeUidGen {
    /// counter for sub-second IDs generated.
    ///
    /// Only 10 bits are actually used.
    counter: u16,

    /// Contains second number of last generated ID.
    /// If new ID is generated in the same second, counter is incremented.
    /// Otherwise new second is used and counter is reset.
    ///
    /// Only 34 bits are actually used.
    second: u64,

    /// Generator ID.
    /// Used to avoid collisions between different instances.
    ///
    /// Only 20 bits are actually used.
    generator_id: u32,

    /// Start time for the generator.
    start: SystemTime,
}

impl TimeUidGen {
    pub fn with_start(generator_id: u32, start: SystemTime) -> Self {
        let generator_id = generator_id & 0xFFFFF;

        let now = SystemTime::now();

        // Find second number from the start.
        let second = now
            .duration_since(start)
            .expect("start for TimeUidGen is in the future")
            .as_secs();

        // Counter is initialized in a way that will require
        // second to pass before first ID is generated.
        // This avoids collisions with IDs generated by previous run of the process in the same second.
        TimeUidGen {
            counter: 0x3FF,
            second,
            generator_id,
            start,
        }
    }

    pub fn random_with_start(start: SystemTime) -> Self {
        let generator_id = rand::random::<u32>() & 0xFFFFF;
        TimeUidGen::with_start(generator_id, start)
    }

    pub fn random() -> Self {
        TimeUidGen::random_with_start(SystemTime::UNIX_EPOCH)
    }

    pub fn next(&mut self) -> NonZeroU64 {
        loop {
            let now = SystemTime::now();
            let second = now
                .duration_since(self.start)
                .expect("TimeUidGen start is in the future")
                .as_secs();

            if second > 0x3FFFFFFFF {
                panic!("Too distant future");
            }

            if second != self.second {
                self.second = second;
                self.counter = 0;
            }

            self.counter = self.counter.wrapping_add(1);
            if self.counter & 0x3FF == 0 {
                // In rare case when we generate IDs faster than one per millisecond
                // we need to wait for next second.
                let next_second = self.start + Duration::from_secs(second + 1);
                let duration = next_second.duration_since(now).unwrap();
                sleep(duration);
                continue;
            }

            self.second = second;

            let counter = (self.counter & 0x3FF) as u64;
            let second = self.second & 0x3FFFFFFFF;
            let generator_id = (self.generator_id & 0xFFFFF) as u64;

            let id = (second << 30) | (counter << 20) | generator_id;

            // counter is never 0.
            return NonZeroU64::new(id).unwrap();
        }
    }
}

impl GenId for TimeUidGen {
    type Value = NonZeroU64;

    #[inline(always)]
    fn generate(&mut self) -> NonZeroU64 {
        self.next()
    }
}

impl GenUid for TimeUidGen {}
