[package]
name = "arcana-intern"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "Arcana Library for interning strings"

[dependencies]
foldhash.workspace = true
hashbrown.workspace = true
parking_lot.workspace = true
serde.workspace = true
unicode-ident.workspace = true
