[package]
name = "arcana-metatype"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true

[features]
probe = ["dep:egui", "dep:egui-probe"]

[dependencies]
arcana-id = { path = "../id" }
arcana-proc = { path = "../proc" }

egui = { workspace = true, optional = true }
egui-probe = { workspace = true, optional = true }
