[package]
name = "platformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nothing = { path = "../../engine", features = ["derive", "gilrs", "tokio-multi-thread"] }
