mod meta;

pub use self::meta::Meta;

use arcana_id::make_uid;

make_uid! {
    /// Stable Type Identifier.
    ///
    /// Identifier is assigned via `HasStid` trait.
    /// The trait can be implemented manually, derived or implemented by `has_stid!` macro.
    ///
    /// Derive macro and proc-macro allow specifying the identifier value.
    /// If not specified, the value is generated by hashing macro input with stable hash.
    pub Stid;
}

impl Stid {
    #[inline(always)]
    pub fn of<T: ?Sized + MetaType>() -> Self {
        T::META.stid
    }
}

#[cfg(feature = "probe")]
pub struct MetaProbeInfo {
    #[cfg(feature = "probe")]
    pub probe: fn(&mut Meta, ui: &mut egui::Ui, style: &egui_probe::Style),

    #[cfg(feature = "probe")]
    pub iterate_inner: fn(
        &mut self,
        ui: &mut egui::Ui,
        f: &mut dyn FnMut(&str, &mut egui::Ui, &mut dyn egui_probe::EguiProbe),
    ),
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct MetaTypeInfo {
    /// Stable Type Identifier.
    pub stid: Stid,

    /// Name of the type.
    pub name: &'static str,

    /// Volatile version of the type.
    /// This version is incremented when type is recompiled and code can assume that type changed.
    /// If `volatile_version` is unchanged, the type instances can be safely reused.
    /// Version is reset when workspace is cleaned.
    pub volatile_version: u64,

    /// Optional function to create a default instance of the type.
    pub make_default: Option<fn() -> Meta>,

    #[cfg(feature = "probe")]
    pub probe: Option<fn(&mut Meta) -> &mut dyn egui_probe::EguiProbe>,
}

pub struct MetaField {
    pub name: &'static str,
    pub stid: Stid,
}

pub trait MetaType: 'static {
    const META: MetaTypeInfo;

    #[inline(always)]
    fn stid() -> Stid {
        Self::META.stid
    }

    #[inline(always)]
    fn name() -> &'static str {
        Self::META.name
    }
}

#[cfg(not(feature = "probe"))]
#[macro_export]
macro_rules! primitive_meta {
    ($name:ident) => {
        impl $crate::MetaType for $name {
            const META: $crate::MetaTypeInfo = $crate::MetaTypeInfo {
                stid: $crate::for_macro::make_stid($crate::for_macro::stable_hash_tokens!($name)),
                name: ::core::stringify!($name),
                volatile_version: 0,
                make_default: None,
            };
        }
    };

    ($name:ident = $default:expr) => {
        impl $crate::MetaType for $name {
            const META: $crate::MetaTypeInfo = $crate::MetaTypeInfo {
                stid: $crate::for_macro::make_stid($crate::for_macro::stable_hash_tokens!($name)),
                name: ::core::stringify!($name),
                volatile_version: 0,
                make_default: Some(move || $default),
            };
        }
    };
    ($name:ident : impl EguiProbe) => {
        $crate::primitive_meta!($name);
    };
    ($name:ident : impl EguiProbe = $default:expr) => {
        $crate::primitive_meta!($name = $default);
    };
}

#[cfg(feature = "probe")]
#[macro_export]
macro_rules! primitive_meta {
    ($name:ident) => {
        impl $crate::MetaType for $name {
            const META: $crate::MetaTypeInfo = $crate::MetaTypeInfo {
                stid: $crate::for_macro::make_stid($crate::for_macro::stable_hash_tokens!($name)),
                name: ::core::stringify!($name),
                volatile_version: 0,
                make_default: None,
                probe: None,
            };
        }
    };

    ($name:ident = $default:expr) => {
        impl $crate::MetaType for $name {
            const META: $crate::MetaTypeInfo = $crate::MetaTypeInfo {
                stid: $crate::for_macro::make_stid($crate::for_macro::stable_hash_tokens!($name)),
                name: ::core::stringify!($name),
                volatile_version: 0,
                make_default: Some(move || $default),
                probe: None,
            };
        }
    };
    ($name:ident : impl EguiProbe) => {
        impl $crate::MetaType for $name {
            const META: $crate::MetaTypeInfo = $crate::MetaTypeInfo {
                stid: $crate::for_macro::make_stid($crate::for_macro::stable_hash_tokens!($name)),
                name: ::core::stringify!($name),
                volatile_version: 0,
                make_default: None,
                probe: Some(|meta: &mut $crate::Meta| meta.downcast_mut::<$name>().unwrap()),
            };
        }
    };

    ($name:ident : impl EguiProbe = $default:expr) => {
        impl $crate::MetaType for $name {
            const META: $crate::MetaTypeInfo = $crate::MetaTypeInfo {
                stid: $crate::for_macro::make_stid($crate::for_macro::stable_hash_tokens!($name)),
                name: ::core::stringify!($name),
                volatile_version: 0,
                make_default: Some(move || $default),
                probe: Some(|meta: &mut $crate::Meta| meta.downcast_mut::<$name>().unwrap()),
            };
        }
    };
}

#[doc(hidden)]
pub mod for_macro {
    pub use arcana_proc::stable_hash_tokens;

    pub const fn make_stid(hash: u64) -> super::Stid {
        crate::Stid::new(core::num::NonZeroU64::new(hash).unwrap())
    }
}
