[package]
name = "code"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
arcana-id = { path = "../id" }
arcana-intern = { path = "../intern" }
arcana-model = { path = "../model" }
arcana-tany = { path = "../tany" }

edict.workspace = true
hashbrown.workspace = true
serde = { workspace = true, features = ["derive"] }
smallvec.workspace = true
tracing.workspace = true
