[package]
name = "arcana-ecs"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "Extension of Edict ECS for Arcana Engine"

[dependencies]
arcana-id = { path = "../id" }
arcana-proc = { path = "../proc" }

edict = { workspace = true, features = ["flow", "serde"] }
gametime.workspace = true
