[package]
name = "bob-dyn"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "bob"
crate-type = ["dylib"]

[dependencies]
bob = { path = "../bob", features = ["derive", "client"] }
