use std::{fmt, io, path::Path};

use arcana_error::{Error, UnifyError};
use camino::{Utf8Path, Utf8PathBuf, absolute_utf8};

use crate::{WORKSPACE_DIR_NAME, dependency::Dependency, path::make_relative, plugin::Plugin};

struct ArcanaDependency<'a>(&'a Dependency);

impl fmt::Display for ArcanaDependency<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            Dependency::Crates(version) => write!(f, "\"{}\"", version),
            Dependency::Git { git, branch } => {
                if let Some(branch) = branch {
                    write!(f, "{{ git = \"{git}\", branch = \"{branch}\" }}")
                } else {
                    write!(f, "{{ git = \"{git}\" }}")
                }
            }
            Dependency::Path { path } => {
                write!(f, "{{ path = \"{}\" }}", path.as_str().escape_default())
            }
        }
    }
}

/// Generates new plugin crate.
///
/// This crate would be placed in the `crates/plugins` directory in the project root.
pub fn new_plugin_crate(
    name: &str,
    path: &Utf8Path,
    engine: Dependency,
    root: Option<&Path>,
) -> Result<Plugin, Error> {
    if path.exists() {
        return Err(Error::msg(format!(
            "Cannot create plugin crate. Path '{}' already exists",
            path
        )));
    }

    std::fs::create_dir_all(&path).map_err(|error| {
        Error::msg(format!(
            "Failed to create plugin directory: '{}'. {error:?}",
            path
        ))
    })?;

    let engine = match root {
        None => engine.make_relative(path),
        Some(root) => engine.make_relative_from(root, path),
    }?;

    #[rustfmt::skip]
    let mut cargo_toml = format!(
r#"[package]
version = "0.0.0"
name = "{name}"
edition = "2021"
publish = false

[dependencies]
arcana = {engine}
"#,
        engine = ArcanaDependency(&engine)
    );

    let cargo_toml_path = path.join("Cargo.toml");
    write_file(&cargo_toml_path, &cargo_toml).map_err(|error| {
        Error::msg(format!(
            "Failed to create plugin file: '{}'. {error:?}",
            cargo_toml_path
        ))
    })?;

    let src_path = path.join("src");
    std::fs::create_dir_all(&src_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create plugin source directory: '{}'. {error:?}",
            src_path
        ))
    })?;

    #[rustfmt::skip]
    let lib_rs = format!(
r#"
// This line allows this crate to function as a plugin for Arcana Engine.
arcana::plugin::declare_plugin!();
"#
    );

    let lib_rs_path = src_path.join("lib.rs");
    write_file(&lib_rs_path, &lib_rs).map_err(|error| {
        Error::msg(format!(
            "Failed to create plugin file: '{}'. {error:?}",
            lib_rs_path
        ))
    })?;

    Plugin::open_local(path.to_owned())
}

/// Generates workspace for the project.
///
/// Workspace consists of:
/// - `ed` crate
///   A simple executable that runs editor.
/// - `plugins` crate
///   A cdylib that links all added plugin crates together.
/// - `game` crate
///   A binary that runs the game without editor.
pub fn init_workspace(
    root: &Path,
    name: &str,
    engine: &Dependency,
    plugins: &[Plugin],
) -> Result<(), Error> {
    let workspace = root.join(WORKSPACE_DIR_NAME);
    std::fs::create_dir_all(&*workspace).map_err(|error| {
        Error::msg(format!(
            "Failed to create project workspace directory: '{}'. {error:?}",
            workspace.display()
        ))
    })?;

    let gitignore = "crates\nArcana.bin.bak\n";
    let gitignore_path = workspace.join(".gitignore");
    std::fs::write(&gitignore_path, gitignore).map_err(|error| {
        Error::msg(format!(
            "Failed to create project workspace .gitignore: '{}'. {error:?}",
            workspace.display()
        ))
    })?;

    let engine = engine
        .clone()
        .make_relative_from(root, WORKSPACE_DIR_NAME)
        .unify_error()?;

    let ed = match engine.clone() {
        Dependency::Path { path } => {
            let path = absolute_utf8(path.join("../../ed")).unwrap();

            Dependency::Path { path }
        }
        engine => engine,
    };

    #[rustfmt::skip]
    let cargo_toml = format!(
r#"# This file is automatically generated for Arcana Project.
# It should not require manual editing.
# If manual editing is required, consider posting your motivation in new GitHub issue
# [{gh_issue}]

[workspace]
resolver = "2"
members = ["plugins", "ed", "game"]

[workspace.dependencies]
arcana = {arcana}
arcana-ed = {arcana_ed}
windows-sys = "0.61"
"#,
        gh_issue = github_autogen_issue_template("workspace Cargo.toml"),
        arcana = ArcanaDependency(&engine),
        arcana_ed = ArcanaDependency(&ed),
    );

    let cargo_toml_path = workspace.join("Cargo.toml");
    write_file(&cargo_toml_path, &cargo_toml).map_err(|error| {
        Error::msg(format!(
            "Failed to create project workspace Cargo.toml: '{}'. {error:?}",
            cargo_toml_path.display()
        ))
    })?;

    let rust_toolchain = r#"[toolchain]
channel = "nightly"
    "#;

    let rust_toolchain_path = workspace.join("rust-toolchain.toml");
    write_file(&rust_toolchain_path, &rust_toolchain).map_err(|error| {
        Error::msg(format!(
            "Failed to create project workspace rust-toolchain.toml: '{}'. {error:?}",
            rust_toolchain_path.display()
        ))
    })?;

    init_ed_crate(root, &workspace, plugins)?;
    init_plugins_crate(root, &workspace, plugins)?;
    init_game_crate(root, &workspace, name, plugins)?;

    Ok(())
}

/// Generates ed crate
fn init_ed_crate(root: &Path, workspace: &Path, plugins: &[Plugin]) -> Result<(), Error> {
    let plugins_path = workspace.join("plugins");

    let ed_path = workspace.join("ed");

    std::fs::create_dir_all(&ed_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create project ed crate directory: '{}'. {error:?}",
            ed_path.display()
        ))
    })?;

    #[rustfmt::skip]
    let mut cargo_toml = format!(
r#"# This file is automatically generated for Arcana Project.
# It should not require manual editing.
# If manual editing is required, consider posting your motivation in new GitHub issue
# [{gh_issue}]
[package]
name = "ed"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
arcana = {{ workspace = true }}
arcana-ed = {{ workspace = true }}

[target.'cfg(windows)'.dependencies]
windows-sys = {{ workspace = true }}
"#,
        gh_issue = github_autogen_issue_template("ed/Cargo.toml")
    );

    // for plugin in plugins {
    //     let dep = plugin
    //         .dependency
    //         .clone()
    //         .make_relative_from(root, &plugins_path)
    //         .unify_error()?;

    //     cargo_toml.push_str(&format!(
    //         "{name} = {dependency}\n",
    //         name = &plugin.name,
    //         dependency = ArcanaDependency(&dep)
    //     ));
    // }

    let cargo_toml_path = ed_path.join("Cargo.toml");
    write_file(&cargo_toml_path, &cargo_toml).map_err(|error| {
        Error::msg(format!(
            "Failed to create project ed crate Cargo.toml '{}'. {error:?}",
            cargo_toml_path.display()
        ))
    })?;

    let src_path = ed_path.join("src");
    std::fs::create_dir_all(&src_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create project ed crate src directory: '{}'. {error:?}",
            src_path.display()
        ))
    })?;

    #[rustfmt::skip]
    let main_rs = format!(
r#"//! This file is automatically generated for Arcana Project.
//! It should not require manual editing.
//! If manual editing is required, consider posting your motivation in new GitHub issue
//! [{gh_issue}]

#![cfg_attr(windows, windows_subsystem = "windows")]

fn main() {{
    #[cfg(windows)]
    {{
        use windows_sys::Win32::System::Console::AttachConsole;

        unsafe {{
            AttachConsole(u32::MAX); // ATTACH_PARENT_PROCESS
        }}
    }}

    eprintln!("Starting Arcana Editor...");

    let mut args = std::env::args_os();

    if args.len() < 2 {{
        eprintln!("Project path is required as the first argument");
        return;
    }}

    let _exe_path = args.next().unwrap();
    let project_path = args.next().unwrap();

    arcana_ed::run(&project_path);
}}
"#,
        gh_issue = github_autogen_issue_template("ed/src/main.rs")
    );

    let main_rs_path = src_path.join("main.rs");
    write_file(&main_rs_path, &main_rs).map_err(|error| {
        Error::msg(format!(
            "Failed to create project ed crate source: '{}'. {error:?}",
            main_rs_path.display()
        ))
    })?;

    Ok(())
}

/// Generates plugins crate.
///
/// Plugins crate is a cdylib that links all plugin crates together.
fn init_plugins_crate(root: &Path, workspace: &Path, plugins: &[Plugin]) -> Result<(), Error> {
    let plugins_path = workspace.join("plugins");

    std::fs::create_dir_all(&plugins_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create project plugins crate directory: '{}'. {error:?}",
            plugins_path.display()
        ))
    })?;

    #[rustfmt::skip]
    let mut cargo_toml = format!(
r#"# This file is automatically generated for Arcana Project.
# It should not require manual editing.
# If manual editing is required, consider posting your motivation in new GitHub issue
# [{gh_issue}]
[package]
name = "plugins"
version = "0.0.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arcana = {{ workspace = true }}
arcana-ed = {{ workspace = true }}
"#,
        gh_issue = github_autogen_issue_template("plugins/Cargo.toml")
    );

    for plugin in plugins {
        let dep = plugin
            .dependency
            .clone()
            .make_relative_from(root, &plugins_path)
            .unify_error()?;

        cargo_toml.push_str(&format!(
            "{name} = {dependency}\n",
            name = &plugin.name,
            dependency = ArcanaDependency(&dep)
        ));
    }

    let cargo_toml_path = plugins_path.join("Cargo.toml");
    write_file(&cargo_toml_path, &cargo_toml).map_err(|error| {
        Error::msg(format!(
            "Failed to create project plugins crate Cargo.toml '{}'. {error:?}",
            cargo_toml_path.display()
        ))
    })?;

    let src_path = plugins_path.join("src");
    std::fs::create_dir_all(&src_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create project plugins crate src directory: '{}'. {error:?}",
            src_path.display()
        ))
    })?;

    #[rustfmt::skip]
    let mut lib_rs = format!(
r#"//! This file is automatically generated for Arcana Project.
//! It should not require manual editing.
//! If manual editing is required, consider posting your motivation in new GitHub issue
//! [{gh_issue}]

#[no_mangle]
pub fn arcana_version() -> &'static str {{
    arcana::version()
}}

#[no_mangle]
pub fn arcana_linked(check: &::core::sync::atomic::AtomicBool) -> bool {{
    arcana::plugin::running_arcana_instance_check(check)
}}

#[no_mangle]
pub fn arcana_plugins() -> Vec<(arcana::Name, arcana::plugin::ArcanaPlugin)> {{
    let plugins = vec!["#,
        gh_issue = github_autogen_issue_template("plugins/src/lib.rs"),
    );

    if !plugins.is_empty() {
        lib_rs.push('\n');

        for plugin in plugins {
            lib_rs.push_str(&format!(
                "        (arcana::name!({name}), {ident}::arcana_plugin::get()),\n",
                name = plugin.name,
                ident = plugin.ident,
            ));
        }
    }

    lib_rs.push_str(
        r#"    ];
    plugins
}"#,
    );

    let lib_rs_path = src_path.join("lib.rs");
    write_file(&lib_rs_path, &lib_rs).map_err(|error| {
        Error::msg(format!(
            "Failed to create project plugins crate source: '{}'. {error:?}",
            lib_rs_path.display()
        ))
    })?;

    Ok(())
}

/// Generates game crate
fn init_game_crate(
    root: &Path,
    workspace: &Path,
    name: &str,
    plugins: &[Plugin],
) -> Result<(), Error> {
    let game_path = workspace.join("game");

    std::fs::create_dir_all(&game_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create project game crate directory: '{}'. {error:?}",
            game_path.display()
        ))
    })?;

    let mut cargo_toml = format!(
        r#"# This file is automatically generated for Arcana Project.
# It should not require manual editing.
# If manual editing is required, consider posting your motivation in new GitHub issue
# [{gh_issue}]
[package]
name = "game"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "{name}"
path = "src/main.rs"

[dependencies]
arcana = {{ workspace = true }}

[target.'cfg(windows)'.dependencies]
windows-sys = {{ workspace = true }}
"#,
        gh_issue = github_autogen_issue_template("game/Cargo.toml")
    );

    for plugin in plugins {
        let dep = plugin
            .dependency
            .clone()
            .make_relative_from(root, &game_path)
            .unify_error()?;

        cargo_toml.push_str(&format!(
            "{name} = {dependency}\n",
            name = &plugin.name,
            dependency = ArcanaDependency(&dep)
        ));
    }

    let cargo_toml_path = game_path.join("Cargo.toml");
    write_file(&cargo_toml_path, &cargo_toml).map_err(|error| {
        Error::msg(format!(
            "Failed to create project game crate Cargo.toml '{}'. {error:?}",
            cargo_toml_path.display()
        ))
    })?;

    let src_path = game_path.join("src");
    std::fs::create_dir_all(&src_path).map_err(|error| {
        Error::msg(format!(
            "Failed to create project game crate src directory: '{}'. {error:?}",
            src_path.display()
        ))
    })?;

    let mut main_rs = format!(
        r#"//! This file is automatically generated for Arcana Project.
//! It should not require manual editing.
//! If manual editing is required, consider posting your motivation in new GitHub issue
//! [{gh_issue}]

#![cfg_attr(windows, windows_subsystem = "windows")]

fn main() {{
    #[cfg(windows)]
    {{
        use windows_sys::Win32::System::Console::AttachConsole;

        unsafe {{
            AttachConsole(u32::MAX); // ATTACH_PARENT_PROCESS
        }}
    }}

    const PLUGINS: [arcana::plugin::ArcanaPlugin; {plugins_count}] = ["#,
        gh_issue = github_autogen_issue_template("game/src/main.rs"),
        plugins_count = plugins.len(),
    );

    if !plugins.is_empty() {
        main_rs.push('\n');

        for plugin in plugins {
            main_rs.push_str(&format!(
                "        {ident}::arcana_plugin::get(),\n",
                ident = plugin.ident
            ));
        }
    }

    main_rs.push_str(
        r#"    ];
    arcana::game::run(&PLUGINS);
}"#,
    );

    let main_rs_path = src_path.join("main.rs");
    write_file(&main_rs_path, &main_rs).map_err(|error| {
        Error::msg(format!(
            "Failed to create project game crate source: '{}'. {error:?}",
            main_rs_path.display()
        ))
    })?;

    Ok(())
}

/// Writes content to a file.
/// If new content is the same as old content the file is not modified.
fn write_file<P, C>(path: P, content: C) -> std::io::Result<()>
where
    P: AsRef<Path>,
    C: AsRef<[u8]>,
{
    match std::fs::read(path.as_ref()) {
        Ok(old_content) if old_content == content.as_ref() => {
            return Ok(());
        }
        _ => {}
    }
    std::fs::write(path, content)
}

fn github_autogen_issue_template(file: &str) -> String {
    format!(
        "https://github.com/zakarumych/arcana/issues/new?body=%3C%21--%20Please%2C%20provide%20your%20reason%20to%20edit%20auto-generated%20{file}%20in%20Arcana%20project%20--%3E"
    )
}
