[package]
name = "arcana-id"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
description = "ID types and generators"

[dependencies]
arcana-proc = { path = "../proc" }
arcana-base-encoding = { path = "../base-encoding" }
serde = { workspace = true, features = ["derive"] }
smol_str.workspace = true
thiserror.workspace = true
rand.workspace = true
gametime.workspace = true
edict.workspace = true
vtid = { workspace = true, features = ["derive"] }
palette.workspace = true
